### ISSUE TITLE
clearallstreamers AttributeError: 'BotConfigManager' object has no attribute 'confing'

### ISSUE THREAD

**Issue by rkantos** [eriknyquist/nedry#3]
https://github.com/eriknyquist/nedry/blob/a577d4bad7ad66faf6fba82a49272de15cc9c655/nedry/command_processor.py#L637

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nedry/discord_bot.py", line 110, in on_message
    resp = self.on_mention(message)
  File "/usr/local/lib/python3.9/dist-packages/nedry/discord_bot.py", line 294, in on_mention
    events.emit(EventType.BOT_COMMAND_RECEIVED, message, msg)
  File "/usr/local/lib/python3.9/dist-packages/nedry/events.py", line 96, in emit
    _events[event_type].emit(*event_args, **event_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nedry/events.py", line 49, in emit
    stop_processing_events = handler(*event_args, **event_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nedry/discord_bot.py", line 276, in _on_bot_command_received
    resp = self.cmdprocessor.process_command(discord_message.channel, discord_message.author, cmd_msg)
  File "/usr/local/lib/python3.9/dist-packages/nedry/command_processor.py", line 492, in process_command
    return handler(command, argtext, msg_data, self, self.config, self.twitch_monitor)
  File "/usr/local/lib/python3.9/dist-packages/nedry/command_processor.py", line 637, in cmd_clearallstreamers
    config.confing.streamers_to_monitor.clear()
AttributeError: 'BotConfigManager' object has no attribute 'confing'
```

**Comment by eriknyquist** [comment]
Thanks, will fix it in the next release... gonna wait a couple days this time in case you find more stuff 😄

**Comment by eriknyquist** [comment]
Fixed in latest releases
